version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  kittygram_db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/var/www/kittygram_final/media
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    build: ./nginx/
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/var/www/kittygram_final/media
    ports:
      - 9000:80
